---
abstract: 'The base modue for the Trudy testing suite'
author:
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Trudy
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Config::General: 0
  DBD::SQLite: 0
  File::ShareDir: 0
  Getopt::Long: 0
  Pod::Usage: 0
  Template::Alloy: 0
  XML::LibXML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
